### ISSUE TITLE
Run hugo server --disableFastRender failed

### ISSUE THREAD

**Issue by victory460** [apache/dubbo-website#1305]
## Expected Behavior

Run `hugo server --disableFastRender` successful

## Actual Behavior

```
hugo --panicOnWarning
Start building sites …
hugo v0.101.0-466fa43c16709b4483689930a4f9ac8add5c9f66+extended darwin/amd64 BuildDate=2022-06-16T07:09:16Z VendorInfo=gohugoio
WARN 2022/07/28 23:55:47 The google_news internal template will be removed in a future release. Please remove calls to this template. See https://github.com/gohugoio/hugo/issues/9172 for additional information.
WARN 2022/07/28 23:55:50 .Path when the page is backed by a file is deprecated and will be removed in a future release. We plan to use Path for a canonical source path and you probably want to check the source is a file. To get the current behaviour, you can use a construct similar to the one below:

  {{ $path := "" }}
  {{ with .File }}
	{{ $path = .Path }}
  {{ else }}
	{{ $path = .Path }}
  {{ end }}
ERROR 2022/07/28 23:55:59 render of "page" failed: "/Users/victory/vscode-prjs/dubbo-website/themes/docsy/layouts/docs/baseof.html:17:15": execute of template failed: template: docs/single.html:17:15: executing "docs/single.html" at <partial "page-meta-links.html" .>: error calling partial: "/Users/victory/vscode-prjs/dubbo-website/themes/docsy/layouts/partials/page-meta-links.html:1:6": execute of template failed: template: partials/page-meta-links.html:1:6: executing "partials/page-meta-links.html" at <.Path>: error calling Path: Warning trapped. Remove the --panicOnWarning flag to continue.
Error: Error building site: failed to render pages: render of "page" failed: "/Users/victory/vscode-prjs/dubbo-website/themes/docsy/layouts/docs/baseof.html:4:7": execute of template failed: template: docs/single.html:4:7: executing "docs/single.html" at <partial "head.html" .>: error calling partial: execute of template failed: template: _internal/google_news.html:1:4: executing "_internal/google_news.html" at <warnf "The google_news internal template will be removed in a future release. Please remove calls to this template. See https://github.com/gohugoio/hugo/issues/9172 for additional information.">: error calling warnf: Warning trapped. Remove the --panicOnWarning flag to continue.
Total in 12364 ms
```

## Steps to Reproduce the Problem
I follow the project README.MD.

**Comment by AlbumenJ** [comment]
https://www.docsy.dev/docs/get-started/docsy-as-module/installation-prerequisites/

**Comment by AlbumenJ** [comment]
This may be the issue of hugo.

**Comment by victory460** [comment]
> Try use `git submodule update --init --recursive`.

Thanks a lot, but it's not work .

```
# victory @ victorydeMacBook-Pro in ~/idea-prjs/pr/dubbo-website on git:master o [23:13:07] C:130
$ git submodule update --init --recursive
remote: Enumerating objects: 38209, done.
remote: Counting objects: 100% (38182/38182), done.
remote: Compressing objects: 100% (7578/7578), done.
remote: Total 34101 (delta 29527), reused 30057 (delta 26486), pack-reused 0
接收对象中: 100% (34101/34101), 45.74 MiB | 3.47 MiB/s, 完成.
处理 delta 中: 100% (29527/29527), 完成 786 个本地对象.
来自 https://github.com/FortAwesome/Font-Awesome
 * branch              7d3d774145ac38663f6d1effc6def0334b68ab7e -> FETCH_HEAD
子模组路径 '.github/themes/docsy/assets/vendor/Font-Awesome'：检出 '7d3d774145ac38663f6d1effc6def0334b68ab7e'
remote: Enumerating objects: 126391, done.
remote: Counting objects: 100% (126391/126391), done.
remote: Compressing objects: 100% (40551/40551), done.
remote: Total 126126 (delta 84665), reused 125881 (delta 84420), pack-reused 0
接收对象中: 100% (126126/126126), 129.44 MiB | 4.23 MiB/s, 完成.
处理 delta 中: 100% (84665/84665), 完成 109 个本地对象.
来自 https://github.com/twbs/bootstrap
 * branch                043a03c95a2ad6738f85b65e53b9dbdfb03b8d10 -> FETCH_HEAD
子模组路径 '.github/themes/docsy/assets/vendor/bootstrap'：检出 '043a03c95a2ad6738f85b65e53b9dbdfb03b8d10'

# victory @ victorydeMacBook-Pro in ~/idea-prjs/pr/dubbo-website on git:master o [23:14:57]
$ ls
404.html                     README.md                    assets                       config.toml                  layouts                      static
LICENSE                      archetypes                   baidu_verify_9ea1htgFIo.html content                      package.json                 themes

# victory @ victorydeMacBook-Pro in ~/idea-prjs/pr/dubbo-website on git:master o [23:15:14] C:127
$ nvm ls
        v6.11.3
        v8.11.4
       v16.16.0
default -> v16.16.0
node -> stable (-> v16.16.0) (default)
stable -> 16.16 (-> v16.16.0) (default)
iojs -> N/A (default)
lts/* -> lts/gallium (-> v16.16.0)
lts/argon -> v4.9.1 (-> N/A)
lts/boron -> v6.17.1 (-> N/A)
lts/carbon -> v8.17.0 (-> N/A)
lts/dubnium -> v10.24.1 (-> N/A)
lts/erbium -> v12.22.12 (-> N/A)
lts/fermium -> v14.20.0 (-> N/A)
lts/gallium -> v16.16.0

# victory @ victorydeMacBook-Pro in ~/idea-prjs/pr/dubbo-website on git:master o [23:15:22]
$ nvm use v16.16.0
Now using node v16.16.0 (npm v8.11.0)

# victory @ victorydeMacBook-Pro in ~/idea-prjs/pr/dubbo-website on git:master o [23:15:28]
$ npm install

added 119 packages, and audited 120 packages in 22s

15 packages are looking for funding
  run `npm fund` for details

found 0 vulnerabilities

# victory @ victorydeMacBook-Pro in ~/idea-prjs/pr/dubbo-website on git:master o [23:16:01]
$ hugo server --disableFastRender
Start building sites …
hugo v0.101.0-466fa43c16709b4483689930a4f9ac8add5c9f66+extended darwin/amd64 BuildDate=2022-06-16T07:09:16Z VendorInfo=gohugoio
WARN 2022/07/31 23:16:09 The google_news internal template will be removed in a future release. Please remove calls to this template. See https://github.com/gohugoio/hugo/issues/9172 for additional information.
WARN 2022/07/31 23:16:09 .Path when the page is backed by a file is deprecated and will be removed in a future release. We plan to use Path for a canonical source path and you probably want to check the source is a file. To get the current behaviour, you can use a construct similar to the one below:

  {{ $path := "" }}
  {{ with .File }}
	{{ $path = .Path }}
  {{ else }}
	{{ $path = .Path }}
  {{ end }}


Re-run Hugo with the flag --panicOnWarning to get a better error message.
WARN 2022/07/31 23:16:18 The google_news internal template will be removed in a future release. Please remove calls to this template. See https://github.com/gohugoio/hugo/issues/9172 for additional information.
WARN 2022/07/31 23:16:18 "/Users/victory/idea-prjs/pr/dubbo-website/content/en/latest/community/_index.md:1:1": duplicate menu entry with identifier "Community" in menu "main"
WARN 2022/07/31 23:16:18 "/Users/victory/idea-prjs/pr/dubbo-website/content/en/latest/facade-docs/_index.md:1:1": duplicate menu entry with identifier "Documentation" in menu "main"
WARN 2022/07/31 23:16:20 .File.UniqueID on zero object. Wrap it in if or with: {{ with .File }}{{ .UniqueID }}{{ end }}

                   |  ZH  | EN
-------------------+------+------
  Pages            | 1139 | 397
  Paginator pages  |   22 |   7
  Non-page files   |    1 |   1
  Static files     |  811 | 811
  Processed images |    2 |   2
  Aliases          |   10 |   3
  Sitemaps         |    2 |   1
  Cleaned          |    0 |   0

Built in 11495 ms
Watching for changes in /Users/victory/idea-prjs/pr/dubbo-website/{archetypes,assets,content,layouts,package.json,static,themes}
Watching for config changes in /Users/victory/idea-prjs/pr/dubbo-website/config.toml, /Users/victory/idea-prjs/pr/dubbo-website/themes/docsy/config.toml
fatal error: pipe failed

goroutine 1 [running]:
runtime.throw({0x5cf2455?, 0xc0004fe900?})
	/usr/local/go/src/runtime/panic.go:992 +0x71 fp=0xc02a6cf840 sp=0xc02a6cf810 pc=0x4035db1
runtime.sigNoteSetup(0xc02a6cf8a0)
	/usr/local/go/src/runtime/os_darwin.go:101 +0xc5 fp=0xc02a6cf868 sp=0xc02a6cf840 pc=0x4032e85
os/signal.signal_enable(0x2)
	/usr/local/go/src/runtime/sigqueue.go:202 +0x39 fp=0xc02a6cf888 sp=0xc02a6cf868 pc=0x4065219
os/signal.enableSignal(...)
	/usr/local/go/src/os/signal/signal_unix.go:49
os/signal.Notify.func1(0x5a64900?)
	/usr/local/go/src/os/signal/signal.go:145 +0x73 fp=0xc02a6cf8b0 sp=0xc02a6cf888 pc=0x5699693
os/signal.Notify(0xc01688f740, {0xc02a6cfb58, 0x2, 0x4065865?})
	/usr/local/go/src/os/signal/signal.go:165 +0x1ff fp=0xc02a6cf928 sp=0xc02a6cf8b0 pc=0x569955f
github.com/gohugoio/hugo/commands.(*commandeer).serve(0xc0003954a0, 0xc000051480)
	/root/project/hugo/commands/server.go:573 +0x509 fp=0xc02a6cfb90 sp=0xc02a6cf928 pc=0x56ce129
github.com/gohugoio/hugo/commands.(*serverCmd).server(0xc000051480, 0xc00030c780, {0xc000124500?, 0x4590620?, 0xc0009bfd00?})
	/root/project/hugo/commands/server.go:297 +0x3c8 fp=0xc02a6cfcd8 sp=0xc02a6cfb90 pc=0x56ca688
github.com/gohugoio/hugo/commands.(*commandsBuilder).newServerCmdSignaled.func1(0xc00030c780?, {0xc0002ca090?, 0x1?, 0x1?})
	/root/project/hugo/commands/server.go:96 +0x36 fp=0xc02a6cfd28 sp=0xc02a6cfcd8 pc=0x56ca156
github.com/spf13/cobra.(*Command).execute(0xc00030c780, {0xc0002ca070, 0x1, 0x1})
	/go/pkg/mod/github.com/spf13/cobra@v1.4.0/command.go:856 +0x67c fp=0xc02a6cfe00 sp=0xc02a6cfd28 pc=0x458fbfc
github.com/spf13/cobra.(*Command).ExecuteC(0xc0004faf00)
	/go/pkg/mod/github.com/spf13/cobra@v1.4.0/command.go:974 +0x3b4 fp=0xc02a6cfeb8 sp=0xc02a6cfe00 pc=0x4590274
github.com/gohugoio/hugo/commands.Execute({0xc0001940a0, 0x2, 0x2})
	/root/project/hugo/commands/hugo.go:92 +0xb4 fp=0xc02a6cff38 sp=0xc02a6cfeb8 pc=0x56b66d4
main.main()
	/root/project/hugo/main.go:23 +0x57 fp=0xc02a6cff80 sp=0xc02a6cff38 pc=0x56d3cd7
runtime.main()
	/usr/local/go/src/runtime/proc.go:250 +0x212 fp=0xc02a6cffe0 sp=0xc02a6cff80 pc=0x4038492
runtime.goexit()
	/usr/local/go/src/runtime/asm_amd64.s:1571 +0x1 fp=0xc02a6cffe8 sp=0xc02a6cffe0 pc=0x40692c1

goroutine 9 [select]:
go.opencensus.io/stats/view.(*worker).start(0xc000122c80)
	/go/pkg/mod/go.opencensus.io@v0.23.0/stats/view/worker.go:276 +0xad
created by go.opencensus.io/stats/view.init.0
	/go/pkg/mod/go.opencensus.io@v0.23.0/stats/view/worker.go:34 +0x8d

goroutine 1541 [select]:
github.com/gohugoio/hugo/watcher.(*Batcher).run(0xc012857770)
	/root/project/hugo/watcher/batcher.go:67 +0x11a
created by github.com/gohugoio/hugo/watcher.New
	/root/project/hugo/watcher/batcher.go:56 +0x1ed

goroutine 1540 [syscall]:
syscall.syscall6(0xc004ca94a0?, 0x4015426?, 0x35969200?, 0x5cc9cdd?, 0x359dcfff?, 0xc004ca9590?, 0x800?)
	/usr/local/go/src/runtime/sys_darwin.go:44 +0x6a
golang.org/x/sys/unix.kevent(0x203006?, 0x800?, 0x800?, 0x4000?, 0x359dcfff?, 0x35969400?)
	/go/pkg/mod/golang.org/x/sys@v0.0.0-20220520151302-bc2c85ada10a/unix/zsyscall_darwin_amd64.go:276 +0x52
golang.org/x/sys/unix.Kevent(0x40186ab?, {0x0?, 0x40670ce?, 0x4038907?}, {0xc004ca9678?, 0x4007c05?, 0xc004ca9588?}, 0x400c72b?)
	/go/pkg/mod/golang.org/x/sys@v0.0.0-20220520151302-bc2c85ada10a/unix/syscall_bsd.go:399 +0x3c
github.com/fsnotify/fsnotify.read(0xc000580000?, {0xc004ca9678?, 0xc006dc8000?, 0xa}, 0xc004ca9618?)
	/go/pkg/mod/github.com/fsnotify/fsnotify@v1.5.4/kqueue.go:525 +0x3f
github.com/fsnotify/fsnotify.(*Watcher).readEvents(0xc015d74960)
	/go/pkg/mod/github.com/fsnotify/fsnotify@v1.5.4/kqueue.go:288 +0xa5
created by github.com/fsnotify/fsnotify.NewWatcher
	/go/pkg/mod/github.com/fsnotify/fsnotify@v1.5.4/kqueue.go:63 +0x1c5

goroutine 1542 [select]:
github.com/gohugoio/hugo/commands.(*commandeer).newWatcher.func1()
	/root/project/hugo/commands/hugo.go:888 +0xf9
created by github.com/gohugoio/hugo/commands.(*commandeer).newWatcher
	/root/project/hugo/commands/hugo.go:886 +0x3ca

goroutine 1543 [select]:
github.com/gohugoio/hugo/livereload.(*hub).run(0x7368940)
	/root/project/hugo/livereload/hub.go:39 +0xec
created by github.com/gohugoio/hugo/livereload.Initialize
	/root/project/hugo/livereload/livereload.go:105 +0x3f



# victory @ victorydeMacBook-Pro in ~/idea-prjs/pr/dubbo-website on git:master o [23:16:20] C:2
$ hugo --panicOnWarning
Start building sites …
hugo v0.101.0-466fa43c16709b4483689930a4f9ac8add5c9f66+extended darwin/amd64 BuildDate=2022-06-16T07:09:16Z VendorInfo=gohugoio
WARN 2022/07/31 23:18:55 The google_news internal template will be removed in a future release. Please remove calls to this template. See https://github.com/gohugoio/hugo/issues/9172 for additional information.
WARN 2022/07/31 23:18:58 .Path when the page is backed by a file is deprecated and will be removed in a future release. We plan to use Path for a canonical source path and you probably want to check the source is a file. To get the current behaviour, you can use a construct similar to the one below:

  {{ $path := "" }}
  {{ with .File }}
	{{ $path = .Path }}
  {{ else }}
	{{ $path = .Path }}
  {{ end }}
ERROR 2022/07/31 23:19:06 render of "page" failed: "/Users/victory/idea-prjs/pr/dubbo-website/themes/docsy/layouts/docs/baseof.html:17:15": execute of template failed: template: docs/single.html:17:15: executing "docs/single.html" at <partial "page-meta-links.html" .>: error calling partial: "/Users/victory/idea-prjs/pr/dubbo-website/themes/docsy/layouts/partials/page-meta-links.html:1:6": execute of template failed: template: partials/page-meta-links.html:1:6: executing "partials/page-meta-links.html" at <.Path>: error calling Path: Warning trapped. Remove the --panicOnWarning flag to continue.
Error: Error building site: failed to render pages: render of "page" failed: "/Users/victory/idea-prjs/pr/dubbo-website/themes/docsy/layouts/docs/baseof.html:4:7": execute of template failed: template: docs/single.html:4:7: executing "docs/single.html" at <partial "head.html" .>: error calling partial: execute of template failed: template: _internal/google_news.html:1:4: executing "_internal/google_news.html" at <warnf "The google_news internal template will be removed in a future release. Please remove calls to this template. See https://github.com/gohugoio/hugo/issues/9172 for additional information.">: error calling warnf: Warning trapped. Remove the --panicOnWarning flag to continue.
Total in 11845 ms

# victory @ victorydeMacBook-Pro in ~/idea-prjs/pr/dubbo-website on git:master o [23:19:06] C:255
$ cd themes/docsy/

# victory @ victorydeMacBook-Pro in ~/idea-prjs/pr/dubbo-website/themes/docsy on git:db8f7a7 o [23:19:32]
$ ll
total 72
-rw-r--r--   1 victory  staff   1.2K  7 31 22:56 CONTRIBUTING.md
-rw-r--r--   1 victory  staff    11K  7 31 22:56 LICENSE
-rw-r--r--   1 victory  staff   3.1K  7 31 22:56 README.md
drwxr-xr-x   8 victory  staff   256B  7 31 22:56 assets
-rw-r--r--   1 victory  staff   617B  7 31 22:56 config.toml
drwxr-xr-x  22 victory  staff   704B  7 31 22:56 i18n
drwxr-xr-x   4 victory  staff   128B  7 31 22:56 images
drwxr-xr-x  11 victory  staff   352B  7 31 22:56 layouts
-rw-r--r--   1 victory  staff   464B  7 31 22:56 netlify.toml
-rw-r--r--   1 victory  staff   627B  7 31 22:56 postcss.config.js
drwxr-xr-x   6 victory  staff   192B  7 31 22:56 static
-rw-r--r--   1 victory  staff   384B  7 31 22:56 theme.toml
drwxr-xr-x  15 victory  staff   480B  7 31 22:56 userguide

# victory @ victorydeMacBook-Pro in ~/idea-prjs/pr/dubbo-website/themes/docsy on git:db8f7a7 o [23:19:34]
$
```

**Comment by AlbumenJ** [comment]
How about ask docsy community for help? I have tested hugo v0.87.0 and v0.101.0 and it works fine.

**Comment by victory460** [comment]
> How about ask docsy community for help? I have tested hugo v0.87.0 and v0.101.0 and it works fine.

OK, Thanks.
