### ISSUE TITLE
dubbo version: 3.1.7,  异步调用 异常

### ISSUE THREAD

**Issue by ll21121** [apache/dubbo-website#2667]
dubbo version: 3.1.7,

 public R<Void> test( ) throws ExecutionException, InterruptedException {
        // CompletableFuture<Boolean> future = RpcContext.getContext().asyncCall(
        //     () ->
        // );
        // iMbSpaceSynService.saveAndSyn(bo);
        CompletableFuture<String> future = RpcContext.getServiceContext().asyncCall(
            () -> {
               return asyncService.sayHello("oneway call request1");
            }
        );

        return toAjax(future.get() != null);

    }

Caused by: java.lang.IllegalArgumentException: [Serialization Security] Serialized class java.util.concurrent.CompletableFuture has not implement Serializable interface. Current mode is strict check, will disallow to deserialize it by default. 
	at org.apache.dubbo.common.utils.DefaultSerializeClassChecker.loadClass(DefaultSerializeClassChecker.java:112)
	at org.apache.dubbo.common.serialize.hessian2.Hessian2SerializerFactory.getDefaultSerializer(Hessian2SerializerFactory.java:49)
	at com.alibaba.com.caucho.hessian.io.SerializerFactory.getSerializer(SerializerFactory.java:393)
	at com.alibaba.com.caucho.hessian.io.Hessian2Output.writeObject(Hessian2Output.java:411)
	at com.alibaba.com.caucho.hessian.io.JavaSerializer$FieldSerializer.serialize(JavaSerializer.java:302)
	... 12 common frames omitted

**Comment by AlbumenJ** [comment]
Cloud you pls provide a demo based on 3.2.2?
