### ISSUE TITLE
Protobuf报错，像官网介绍一样引入后报错如下，dubbo版本3.1.10，jdk17

### ISSUE THREAD

**Issue by wsdyk** [apache/dubbo-website#2694]
java.lang.IllegalStateException: No such extension protobuf for serialization/org.apache.dubbo.common.serialize.Serialization
	at org.apache.dubbo.config.utils.ConfigValidationUtils.checkMultiExtension(ConfigValidationUtils.java:680) ~[dubbo-3.1.10.jar:3.1.10]
	at org.apache.dubbo.config.utils.ConfigValidationUtils.checkMultiExtension(ConfigValidationUtils.java:658) ~[dubbo-3.1.10.jar:3.1.10]
	at org.apache.dubbo.config.utils.ConfigValidationUtils.validateProtocolConfig(ConfigValidationUtils.java:574) ~[dubbo-3.1.10.jar:3.1.10]
	at org.apache.dubbo.config.utils.DefaultConfigValidator.validate(DefaultConfigValidator.java:37) ~[dubbo-3.1.10.jar:3.1.10]
	at org.apache.dubbo.config.context.AbstractConfigManager.checkDefaultAndValidateConfigs(AbstractConfigManager.java:588) ~[dubbo-common-3.1.10.jar:3.1.10]
	at org.apache.dubbo.config.context.ConfigManager.checkConfigs(ConfigManager.java:280) ~[dubbo-common-3.1.10.jar:3.1.10]
	at org.apache.dubbo.config.context.ConfigManager.loadConfigs(ConfigManager.java:261) ~[dubbo-common-3.1.10.jar:3.1.10]
	at org.apache.dubbo.config.deploy.DefaultApplicationDeployer.loadApplicationConfigs(DefaultApplicationDeployer.java:225) ~[dubbo-3.1.10.jar:3.1.10]
	at org.apache.dubbo.config.deploy.DefaultApplicationDeployer.initialize(DefaultApplicationDeployer.java:195) ~[dubbo-3.1.10.jar:3.1.10]
	at org.apache.dubbo.config.deploy.DefaultModuleDeployer.prepare(DefaultModuleDeployer.java:479) ~[dubbo-3.1.10.jar:3.1.10]
	at org.apache.dubbo.config.spring.context.DubboConfigApplicationListener.initDubboConfigBeans(DubboConfigApplicationListener.java:73) ~[dubbo-3.1.10.jar:3.1.10]
	at org.apache.dubbo.config.spring.context.DubboConfigApplicationListener.onApplicationEvent(DubboConfigApplicationListener.java:59) ~[dubbo-3.1.10.jar:3.1.10]
	at org.apache.dubbo.config.spring.context.DubboConfigApplicationListener.onApplicationEvent(DubboConfigApplicationListener.java:37) ~[dubbo-3.1.10.jar:3.1.10]
	at org.springframework.context.event.SimpleApplicationEventMulticaster.doInvokeListener(SimpleApplicationEventMulticaster.java:176) ~[spring-context-5.3.23.jar:5.3.23]
	at org.springframework.context.event.SimpleApplicationEventMulticaster.invokeListener(SimpleApplicationEventMulticaster.java:169) ~[spring-context-5.3.23.jar:5.3.23]
	at org.springframework.context.event.SimpleApplicationEventMulticaster.multicastEvent(SimpleApplicationEventMulticaster.java:143) ~[spring-context-5.3.23.jar:5.3.23]
	at org.springframework.context.event.SimpleApplicationEventMulticaster.multicastEvent(SimpleApplicationEventMulticaster.java:131) ~[spring-context-5.3.23.jar:5.3.23]
	at org.springframework.context.support.AbstractApplicationContext.registerListeners(AbstractApplicationContext.java:881) ~[spring-context-5.3.23.jar:5.3.23]
	at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:580) ~[spring-context-5.3.23.jar:5.3.23]
	at org.springframework.boot.web.servlet.context.ServletWebServerApplicationContext.refresh(ServletWebServerApplicationContext.java:145) ~[spring-boot-2.6.13.jar:2.6.13]
	at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:745) ~[spring-boot-2.6.13.jar:2.6.13]
	at org.springframework.boot.SpringApplication.refreshContext(SpringApplication.java:420) ~[spring-boot-2.6.13.jar:2.6.13]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:307) ~[spring-boot-2.6.13.jar:2.6.13]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1317) ~[spring-boot-2.6.13.jar:2.6.13]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1306) ~[spring-boot-2.6.13.jar:2.6.13]

**Comment by wsdyk** [comment]
官网地址如下：https://cn.dubbo.apache.org/zh-cn/overview/mannual/java-sdk/reference-manual/serialization/protobuf/

**Comment by AlbumenJ** [comment]
怎么引入的
