### ISSUE TITLE
Apache Dubbo 版本2.5.7 心跳检查报这个问题

### ISSUE THREAD

**Issue by shinebar** [apache/dubbo-website#795]
dubbo-remoting-server-heartbeat-thread-1][WARN][com.alibaba.dubbo.remoting.exchange.support.header.HeartBeatTask][84]: [DUBBO] Exception when heartbeat to remote channel /10.9.65.170:16432, dubbo version: 2.5.7, current host: 10.10.129.186
com.alibaba.dubbo.remoting.RemotingException: Failed to send message Request [id=51, version=2.0.0, twoway=true, event=true, broken=false, data=null] to /10.9.65.170:16432, cause: No such extension com.alibaba.dubbo.common.serialize.Serialization by name hessian2
	at com.alibaba.dubbo.remoting.transport.netty.NettyChannel.send(NettyChannel.java:108) ~[dubbo-2.5.7.jar:2.5.7]
	at com.alibaba.dubbo.remoting.exchange.support.header.HeaderExchangeChannel.send(HeaderExchangeChannel.java:87) ~[dubbo-2.5.7.jar:2.5.7]
	at com.alibaba.dubbo.remoting.exchange.support.header.HeaderExchangeChannel.send(HeaderExchangeChannel.java:77) ~[dubbo-2.5.7.jar:2.5.7]
	at com.alibaba.dubbo.remoting.exchange.support.header.HeartBeatTask.run(HeartBeatTask.java:64) [dubbo-2.5.7.jar:2.5.7]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_181]
	at java.util.concurrent.FutureTask.runAndReset$$$capture(FutureTask.java:308) [?:1.8.0_181]
	at java.util.concurrent.FutureTask.runAndReset(FutureTask.java) [?:1.8.0_181]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:180) [?:1.8.0_181]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:294) [?:1.8.0_181]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_181]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_181]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_181]
Caused by: java.lang.IllegalStateException: No such extension com.alibaba.dubbo.common.serialize.Serialization by name hessian2
	at com.alibaba.dubbo.common.extension.ExtensionLoader.findException(ExtensionLoader.java:489) ~[dubbo-2.5.7.jar:2.5.7]
	at com.alibaba.dubbo.common.extension.ExtensionLoader.createExtension(ExtensionLoader.java:496) ~[dubbo-2.5.7.jar:2.5.7]
	at com.alibaba.dubbo.common.extension.ExtensionLoader.getExtension(ExtensionLoader.java:317) ~[dubbo-2.5.7.jar:2.5.7]
	at com.alibaba.dubbo.remoting.transport.CodecSupport.getSerialization(CodecSupport.java:62) ~[dubbo-2.5.7.jar:2.5.7]
	at com.alibaba.dubbo.remoting.transport.AbstractCodec.getSerialization(AbstractCodec.java:52) ~[dubbo-2.5.7.jar:2.5.7]
	at com.alibaba.dubbo.remoting.exchange.codec.ExchangeCodec.encodeRequest(ExchangeCodec.java:206) ~[dubbo-2.5.7.jar:2.5.7]
	at com.alibaba.dubbo.remoting.exchange.codec.ExchangeCodec.encode(ExchangeCodec.java:68) ~[dubbo-2.5.7.jar:2.5.7]
	at com.alibaba.dubbo.rpc.protocol.dubbo.DubboCountCodec.encode(DubboCountCodec.java:39) ~[dubbo-2.5.7.jar:2.5.7]
	at com.alibaba.dubbo.remoting.transport.netty.NettyCodecAdapter$InternalEncoder.encode(NettyCodecAdapter.java:81) ~[dubbo-2.5.7.jar:2.5.7]
	at org.jboss.netty.handler.codec.oneone.OneToOneEncoder.doEncode(OneToOneEncoder.java:66) ~[netty-3.10.6.Final.jar:?]
	at org.jboss.netty.handler.codec.oneone.OneToOneEncoder.handleDownstream(OneToOneEncoder.java:59) ~[netty-3.10.6.Final.jar:?]
	at org.jboss.netty.channel.DefaultChannelPipeline.sendDownstream(DefaultChannelPipeline.java:591) ~[netty-3.10.6.Final.jar:?]
	at org.jboss.netty.channel.DefaultChannelPipeline$DefaultChannelHandlerContext.sendDownstream(DefaultChannelPipeline.java:784) ~[netty-3.10.6.Final.jar:?]
	at org.jboss.netty.channel.SimpleChannelHandler.writeRequested(SimpleChannelHandler.java:292) ~[netty-3.10.6.Final.jar:?]
	at com.alibaba.dubbo.remoting.transport.netty.NettyHandler.writeRequested(NettyHandler.java:99) ~[dubbo-2.5.7.jar:2.5.7]
	at org.jboss.netty.channel.SimpleChannelHandler.handleDownstream(SimpleChannelHandler.java:254) ~[netty-3.10.6.Final.jar:?]
	at org.jboss.netty.channel.DefaultChannelPipeline.sendDownstream(DefaultChannelPipeline.java:591) ~[netty-3.10.6.Final.jar:?]
	at org.jboss.netty.channel.DefaultChannelPipeline.sendDownstream(DefaultChannelPipeline.java:582) ~[netty-3.10.6.Final.jar:?]
	at org.jboss.netty.channel.Channels.write(Channels.java:704) ~[netty-3.10.6.Final.jar:?]
	at org.jboss.netty.channel.Channels.write(Channels.java:671) ~[netty-3.10.6.Final.jar:?]
	at org.jboss.netty.channel.AbstractChannel.write(AbstractChannel.java:347) ~[netty-3.10.6.Final.jar:?]
	at com.alibaba.dubbo.remoting.transport.netty.NettyChannel.send(NettyChannel.java:98) ~[dubbo-2.5.7.jar:2.5.7]
	... 11 more

**Comment by shinebar** [comment]
不是文档问题

**Comment by zhangyz-hd** [comment]
dubbo的心跳报文的序列化/反序列化方式，是等于提供者在dubbo:protocol中声明的serialization，这就要求消费者端也具备对应的serialization的spi。请检查一下。

**Comment by shinebar** [comment]
<dubbo:protocol name="dubbo" port="${dubbo.provider.port}" dispatcher="message"/> 没有配置序列化协议，默认的使用dubbo的吧
